add software requirements based on podder installed code #PA-663
podder-ai/podder-ai.github.io pull request #15
Opened 2019-06-07 02:27 UTC by tc-minami

Podder-Installer実行時に（インストール済みでなければ）インストールされるソフトウェアの一覧を追加しました。
また、getting-startedフォルダの中に03-requirementsを追加しました。

インストールされるソフトウェア一覧はソースコードを見つつ記載しましたが、抜け漏れなどありましたら教えてください。

ご確認お願いいたします。

2019-06-07 08:47 UTC, eisuke-ueta requested changes
こちら Requirements で新しくファイルを切ったのはなぜでしょうか？ `Install Podder.ai` のところに入れた方が、インストール時に内容を確認できて良いと思っているのですが。

2019-06-07 09:22 UTC, tc-minami commented
こちら今後Requirements関連の情報（Podderやk8s）の推奨スペックが多くなるかなと思い、ページを分けていました。

たしかに `Install Podder.ai` 内の一連の流れで情報を見れたほうが良いと思うので、調整いたします。

2019-06-07 09:37 UTC, tc-minami commented
インストールされるソフトウェア一覧を `install podder.ai` に記述しました。
こちらのほうが読みやすくなっていると思いますので、お手数ですが再度ご確認お願いいたします。

2019-06-07 09:51 UTC, ueta-eisuke commented on v002/getting-started/01-install-podder-ai.md
> +## Before you execute Podder Installer
@tc-minami 
すみませんが、 `Download Podder Installer` の前に `Requirements` のタイトルで入れてください。実際の作業の前に、何をするのか、どのようなものが事前に必要なのかを記載したいです。

2019-06-10 03:07 UTC, tc-minami commented on v002/getting-started/01-install-podder-ai.md
> +## Before you execute Podder Installer
ご確認ありがとうございます！こちら修正完了いたしました。
お手数ですが再度ご確認お願いいたします。

2019-06-10 06:46 UTC, eisuke-ueta approved these changes

2019-06-10 06:47 UTC, ueta-eisuke commented
LGTM

2019-06-10 06:47 UTC, merged