add basic info of json schema for podder project #PA-666
podder-ai/podder-ai.github.io pull request #22
Opened 2019-06-24 02:21 UTC by tc-minami

Best Practice項目を追加し、バリデーションに関する情報を追記しました。
今回はJSON Schemaの基本的な情報を追記するとのことでしたので、Podder内での仕組みというよりJSON Schemaの読み方/書き方の情報としています。

また、Best Practice系の項目が今後増えそうだと思ったため、`getting-started` 内に新しいマークダウンを追加してあります。こちら記述する場所を変更した方が良い場合は教えてください。

JIRA
https://nexusfrontiertech.atlassian.net/browse/PA-666

2019-06-24 03:21 UTC, ueta-eisuke commented on v002/getting-started/03-best-practice.md
> +# Best Practice
Best Practiceは Getting Started と関係がないので、場所を変えて欲しいです。タスクにもベストプラクティスのセクションを設けてとあるので、Release Notes とはと同じ単位で分けてください。<br>
- Best Practice
  - Validation

2019-06-24 03:23 UTC, ueta-eisuke commented on v002/getting-started/03-best-practice.md
> +# Best Practice
あとJSONスキーマの説明もあっても良いと思うですが、それよりはパイプライン上でどのような単位でバリデーションを切って、バリデーションタスクをどこで入れるのかを図とか入れて説明するのが良いと思います。JSONスキーマはCinnamon用で使わない企業もあると思うので。

2019-06-24 03:23 UTC, eisuke-ueta requested changes
コメント残しているので確認をお願いします。

2019-06-24 04:20 UTC, tc-minami commented on v002/getting-started/03-best-practice.md
> +# Best Practice
ありがとうございます！記述場所と内容について調整してみます。
現状タスク単位でバリデーションしていると思いますので、それをどのタイミングでどのように実装しているか調べつつ情報を追記してみますね。

こちらも了解です！
JSONスキーマは必ず入れる（テンプレとしてデフォルトで入れている）と思っていましたが、企業に使うかどうか判断してもらう感じだったんですね。
> JSONスキーマはCinnamon用で使わない企業もあると思うので。

2019-06-25 17:06 UTC, tc-minami commented on v002/getting-started/03-best-practice.md
> +# Best Practice
Podder上で、JSONスキーマでValidationを行うタイミングの情報を追記しました。
(cinnamon-podder-saasのコードを参考にしました）
またファイルの場所の変更＋ Best Practiceのセクションをサイドバーに追加しました。

お手数ですが、Podder場でのCinnamonの使い方の記述が正しいか等再度ご確認お願いします 🙏

2019-06-27 03:43 UTC, eisuke-ueta approved these changes
LGTM

2019-06-27 03:43 UTC, merged